### ISSUE TITLE
it's still working ? i can't create voucher with unifi controller version 5.6.30 ! can you help me ? pls 

### ISSUE THREAD

**Issue by hieunguyenps01** [davidmaitland/unifi-voucher-generator#5]

**Comment by DJM0** [comment]
I haven’t tested this in a few years. Do you get any errors when it fails?

But I will try and test it over the next few days if I can setup a controller.

**Comment by hieunguyenps01** [comment]
It's working. controller version 5 that have a little change. syntax for
$site not working. i must use string be generate from controller.

thanks for your support. your script are working.

Thanks you so much

2018-04-15 21:14 GMT+07:00 David Maitland <notifications@github.com>:

**Comment by DJM0** [comment]
Great! I have updated the repo to make it a bit clearer.

https://github.com/davidmaitland/unifi-voucher-generator/blob/a64bae31214d7b2c7bc7168153853e41d18b3371/unifi-api.sh#L7

**Comment by hieunguyenps01** [comment]
Hi there.

I want rebuild your code for use generate multi site. Have you suggest
something ?

**Comment by DJM0** [comment]
You could easily modify `unifi-api.sh` and `gen.sh` to use environment variables instead of them being defined at the top of the files. Then you could create a simple bash loop to run the `gen.sh` script for every site in a list.

**Comment by hieunguyenps01** [comment]
Hi david.

i have create a lot of file api.sh for many site.

i have create loop like that ! how to run api.sh follow varriables in loop
?
