### ISSUE TITLE
function delete voucher not work !

### ISSUE THREAD

**Issue by songhanpoo** [davidmaitland/unifi-voucher-generator#7]
Hi David

#!/bin/sh

# Files needed
pwd=`pwd`
. $pwd/unifi-api.sh

# Generate vouchers
unifi_login
voucherID=`unifi_create_voucher $time $amount $note`
unifi_get_vouchers $voucherID > vouchers.tmp
unifi_logout

vouchers=`awk -F"[,:]" '{for(i=1;i<=NF;i++){if($i~/_id\042/){print $(i+1)} } }' vouchers.tmp | sed 's/\"//g'`

for id in $vouchers
do
    id=${id:0:24}
done

unifi_login
deleteID=`unifi_delete_voucher $id`
unifi_get_vouchers $deleteID >  vouchers.tmp
unifi_logout

-----------------------------------------------

can you help me ? your function not work ?

**Comment by DJM0** [comment]
The `unifi_delete_voucher` function isn't something we use so it's hard to say what's wrong.

Are you getting any errors?

p.s. you should really fork this project and commit and raise issues on that.

**Comment by songhanpoo** [comment]
Hi David

-------------------------------------------

+ unifi_login
+ curl --tlsv1 --silent --cookie unifi_cookie_tmp --cookie-jar unifi_cookie_tmp --insecure --data '{'\''username'\'':'\''admin'\'', '\''password'\'':'\''Abc@123'\''}' https://192.168.241.129:8443/api/login
{ "data" : [ ] , "meta" : { "rc" : "ok"}}++ unifi_delete_voucher 5b144703d2deae90f3a3eaf5
++ '[' 1 -lt 1 ']'
++ id=5b144703d2deae90f3a3eaf5
++ curl --tlsv1 --silent --cookie unifi_cookie_tmp --cookie-jar unifi_cookie_tmp --insecure --data 'json={'\''cmd'\'':'\''delete-voucher'\'','\''_id'\'':'\''5b144703d2deae90f3a3eaf5'\''}' https://192.168.241.129:8443/api/s/3vgp709b/cmd/hotspot
+ voucherID='{ "data" : [ ] , "meta" : { "rc" : "ok"}}'
+ unifi_logout
+ curl --tlsv1 --silent --cookie unifi_cookie_tmp --cookie-jar unifi_cookie_tmp --insecure https://192.168.241.129:8443/logout
+ rm unifi_cookie_tmp
------------------------------------------------

i dont' know wrong where :(

**Comment by songhanpoo** [comment]
Hi david !

can you get me your example use your delete voucher function ?

i can learn it.
 
please !:(
Thanks
