### ISSUE TITLE
html missing

### ISSUE THREAD

**Issue by remnts** [davidmaitland/unifi-voucher-generator#8]
Hellos i dont see the file vouchers.html

Can you help me

**Comment by DJM0** [comment]
Can you show me what commands you are running with options and the output you're seeing?

**Comment by FPVZaphod** [comment]
`# ./gen.sh `
`{"meta":{"rc":"error","msg":"api.err.Invalid"},"data":[]}+ [ 2 -lt 0 ]`
`+ token=token={"meta":{"rc":"error","msg":"api.err.LoginRequired"},"data":[]}`
`+ [ token={"meta":{"rc":"error","msg":"api.err.LoginRequired"},"data":[]} !=  ]`
`+ other_payload='create_time':token={"meta":{"rc":"error","msg":"api.err.LoginRequired"},"data":[]}`
`+ curl --tlsv1 --silent --cookie unifi_cookie_tmp --cookie-jar unifi_cookie_tmp --insecure --data json={'create_time':token={"meta":{"rc":"error","msg":"api.err.LoginRequired"},"data":[]}} https://192.168.1.10:8443/api/s/default/stat/voucher`
`+ echo curl --tlsv1 --silent --cookie unifi_cookie_tmp --cookie-jar unifi_cookie_tmp --insecure --data json={'create_time':token={"meta":{"rc":"error","msg":"api.err.LoginRequired"},"data":[]}} https://192.168.1.10:8443/api/s/default/stat/voucher`
`+ unifi_logout`
`+ curl --tlsv1 --silent --cookie unifi_cookie_tmp --cookie-jar unifi_cookie_tmp --insecure https://192.168.1.10:8443/logout`
`+ rm unifi_cookie_tmp`
`+ awk -F[,:] {for(i=1;i<=NF;i++){if($i~/code\042/){print $(i+1)} } } vouchers.tmp`
`+ sed s/\"//g`
`+ vouchers=`
`+ [ -e vouchers.html ]`
`+ echo <html><head><link rel="stylesheet" href="style.css" /></head><body>`
`+ echo </body></html>`
`+ [ -e vouchers.tmp ]`
`+ echo Removing vouchers tmp file.`
`Removing vouchers tmp file.`
`+ rm vouchers.tmp`

**Comment by DJM0** [comment]
Have just updated the UniFi API used, tested on 5.12.35 and it works. Can you pull and try again?
