### ISSUE TITLE
html is generated without content

### ISSUE THREAD

**Issue by Superbear88** [davidmaitland/unifi-voucher-generator#9]
Hi,
the html page is generated by the code, but there is nothing inside. 

Controller Version 	5.12.35

After installing curl in debian, i got i to make the html file, but not more :(

**Comment by FPVZaphod** [comment]
Same here, it seems something changed in the API :-(

**Comment by DJM0** [comment]
Have just updated the UniFi API used, tested on 5.12.35 and it works. Can you pull and try again?

**Comment by FPVZaphod** [comment]
Hi! Thanks for fixing!
It seems I had to add in the beginning of gen.sh:

`#!/bin/sh`

`export username=user`
`export password=password`
`export baseurl=https://xxx.xxx.xxx.xxx:8443`
`export site=default`

`# Files needed`
`...`

to make it work?
It works better now, at least the connection to the Controller works. Just in the voucher generation seems to be a little bug:

`# ./gen.sh `
`{"meta":{"rc":"ok"},"data":[]}+ [ 2 -lt 0 ]`
`+ token=token=1581882716`
`+ [ token=1581882716 !=  ]`
`+ other_payload="create_time":token=1581882716`
`+ curl --tlsv1 --silent --cookie /tmp/tmp.ZFGdooScoa --cookie-jar /tmp/tmp.ZFGdooScoa --insecure --data {"create_time":token=1581882716} https://192.168.1.10:8443/api/s/default/stat/voucher`
`+ echo curl --tlsv1 --silent --cookie /tmp/tmp.ZFGdooScoa --cookie-jar /tmp/tmp.ZFGdooScoa --insecure --data {"create_time":token=1581882716} https://192.168.1.10:8443/api/s/default/stat/voucher`
`+ unifi_logout`
`+ curl --tlsv1 --silent --cookie /tmp/tmp.ZFGdooScoa --cookie-jar /tmp/tmp.ZFGdooScoa --insecure https://192.168.1.10:8443/logout`
`+ awk -F[,:] {for(i=1;i<=NF;i++){if($i~/code\042/){print $(i+1)} } } vouchers.tmp`
`+ sed s/\"//g`
`+ vouchers=2398105551`
`1391960987`
`3327322993`
`+ [ -e vouchers.html ]`
`+ echo Removing old vouchers.`
`Removing old vouchers.`
`+ rm vouchers.html`
`+ echo <html><head><link rel="stylesheet" href="style.css" /></head><body>`
`./gen.sh: 39: ./gen.sh: Bad substitution`

I like to automate sending 3 vouchers per day to my sons iPad. What would be cool is to have the possibility to remove unused vouchers before generating new ones. Not sure how to do that, maybe storing them in a text file, and deleting them in the next run?
Thanks again for your effort!

**Comment by DJM0** [comment]
You should only need to set the following that are already in the top of the file:

```
#username=ubnt
#password=ubnt
#baseurl=https://unifi:8443
#site=default
```

Testing on my 5.12.35 controller it work fine on macOS. What OS are you using?

**Comment by FPVZaphod** [comment]
I am using Debian 9 on my Homeserver - but I just tried on my Macbook with Catalina.
It works on the Macbook, but only when I add the "export username=..." and the others in gen.sh. Then the voucher.html is complete, great!
Just wondering why it doesn't work on Debian? Or better: It works 80%, it pulls the vouchers. Only the output to the file has a problem...

**Comment by DJM0** [comment]
I honestly have no idea, would have to spin up a Debian VM to test.

But I'm thinking about rewriting the whole thing at some point in Python or Go maybe, will make it clearer and add in some extra features.

**Comment by FPVZaphod** [comment]
+1 for Python, because it´s anyways on most  of the servers - and it´s quite OS independent. But GO? Sounds very exotic :-D

**Comment by DJM0** [comment]
Well with Go I would just provide binaries, but saying that I am more comfortable with Python anyways

**Comment by FPVZaphod** [comment]
On Python I will be your happy tester :-)
Whats about php? So you can run it in the webbrowser directly, or by commandline?

**Comment by DJM0** [comment]
I won't touch PHP, just personal preference. I could easily expose an web interface / API with Python though. Will focus on a CLI at first though.
